package src.model;

public enum SpriteID {
    BALL_MOVING,
    BALL_STATIC,
    FIELD,
    PLAYER_LEFT_CATCH,
    PLAYER_LEFT_IDLE,
    PLAYER_LEFT_RUNNING,
    PLAYER_LEFT_SHOT,
    PLAYER_RIGHT_CATCH,
    PLAYER_RIGHT_IDLE,
    PLAYER_RIGHT_RUNNING,
    PLAYER_RIGHT_SHOT;
}
